<?php

function headerhtml($titulo = "Indice"){
?>
    <!DOCTYPE HTML>
    <!--
        Stellar by HTML5 UP
        html5up.net | @ajlkn
        Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
    -->
    <html>
        <head>
            <title>Elements - Stellar by HTML5 UP</title>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
            <link rel="stylesheet" href="assets/css/main.css" />
            <noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
        </head>
        <body class="is-preload">
    
            <!-- Wrapper -->
                <div id="wrapper">
    
                    <!-- Header -->
                        <header id="header">
                            <h1><?php echo $titulo; ?></h1>
                        </header>
                    <!-- Main -->
                        <div id="main">

                            <!-- Content -->
                                <section id="content" class="main">    
<?php
}

function footerhtml(){
?>
						</section>

                </div>
                <!-- Footer -->
                <footer id="footer">
						
						<section>
                            <?php
                            if (isset($_SESSION["usuario"])) {
                                echo "<h2>"; print_r($_SESSION["usuario"]); echo "</h2>"; 
                                ?><ul class="actions"><li><a href="logout.php" class="button small">Cerrar sesión</a></li></ul><?php  
                            }
                            ?>       
					</footer>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>
<?php   
}

?>